# Now continuing to last code of Layers we did,
# Here I will create a Class for the same, for better code management 

In [3]:
# standard ML codes name inputs as X

X = [[11.8,-2.6,3.2, -5.0],
       [1.2,4.8,5.6,-6.1],
       [2.0, 5.0, -1.5, 0.6]]  ## assuming this is the input data to the neural network

# Now we are going to define Two Hidden Layers

# we call it hidden, as we programmers are not incharge of how that layer changes on our own,
## but the neural network, optimizers and other params are responsible to operate the hidden layers

class layer_dense:
    def __init__(self):
        pass
    def forward(self,):
        pass
# these are basic methods that we will use in our class    

## Neural Network Class description:

# Initialzing weights . . . 
### The weights are initialized randomly, btw range (-1,1) generally but more tighter/smaller the range

#### The reason we want small values btw -1,1 so we can tune at micro level, bigger values i.e above 1, makes bigger n bigger tunings, and ultimately explosion in values !!!

### Now, our Input data might have values that exclude this range, so we use normalziation methods for the same to scale them accordingly

##### This is the one of core reason of feature scaling too, this we will do in later codes

### When we initialize our layers, we will adhere to principal of keeping our values small, rather than exploding them 


### ------------------------------------------------------------------------------------------------

# Initializing bias . . . 
### In this case we can keep bias initially as zero, but in many cases we might see, the neural input, and weights are so small that ultimately the neuron wont fire much of the big output and having zero bias being added will result overall output as negligible/ zero -- Dead Neural Layer/ Network

## So better bias to be initialized with Non zero number

# Lets Do It !!

In [14]:
import numpy as np

np.random.seed(0)

class layer_dense:
    def __init__(self,n_inputs, n_neurons):
        self.n_neurons = n_neurons
        self.weights = 0.10*np.random.randn(n_inputs, n_neurons) 
        print("Created a hidden layer with "+ str(self.n_neurons)+" neurons")
# here we need the shape we wanna pass for the weights
## i.e we need the size of input coming in, and size of neurons the user want to have
## multiplying 0.10 so we have tighter weightage range
# the actual shape of weights is , n_neurons* n_inputs
# but notice here we are doing opposite,
# the reason is we wont be needing Transpose method during further Forward Pass process

        self.biases = np.zeros((1,n_neurons))
        

    def forward(self,inputs):   # this method will just take the inputs
        self.output = np.dot(inputs, self.weights) + self.biases
        

In [17]:
X = [[11.8,-2.6,3.2, -5.0],
       [1.2,4.8,5.6,-6.1],
       [2.0, 5.0, -1.5, 0.6]]  

# object instantiazation - creating layer 1 
layer1 = layer_dense(4,5)   # takes (input_size, desired_num_neurons)
# input size is the size of each vector inside the batch , here X[0] == 4


Created a hidden layer with 5 neurons


In [18]:
# output of layer 1 is the input of layer 2
# n_neurons is 5 on layer 1, and the output size will be 5 for layer 1
# hence input of layer 2 is 5

layer2 = layer_dense(5,2)

Created a hidden layer with 2 neurons


In [19]:
layer1.forward(X)

print(layer1.output)

[[ 0.02568743  0.29834814 -2.29495758 -0.80543781 -0.38865618]
 [-0.22632314  0.60491415 -0.95917239  1.65329946 -0.34248843]
 [ 0.24016246  0.82861281  0.72622272 -0.97927288 -0.15705039]]


In [ ]:
layer2.forward(X)

print(layer1.output)