# Batches


### Batches give more dynamic capability to run multiple calculations for matrix multiplications


## Another benefit of working with batches is because they helps with generalization:

#### Single Sample:-
#### inputs = [1, 2, 3, 4]  (e.g these are 4 diff values/features  from a unique sensor at a specific time)
#### Now we can convert them to be a Batch of samples to have many readings of sensors at specific point in time. 

### We can provide multiple samples at a time to the machine rather than providing one by one each time


### Batch size = no of samples at a time fit to the neuron




In [3]:
import numpy as np

inputs=[11.8,-2.6,3.2, -5.0]  # single sample

weights = [[0.3,2,0.6, -1.2],[0.1,-2,3.6, 2.6],[0.7,0.1,1.6, -3.2]]
biases=[2,0.2 ,3]

output = np.dot(weights,inputs) + biases    
print("The output of the this neuron is :", output)    


The output of the this neuron is : [ 8.26  5.1  32.12]


## If batch_size = 1 (1 sample at a time)
## Total Datapoints/samples = 512

### If we as a single neuron to attempt to fit one sample at a time and find a best fit line from the operation
### It will be really a hard time for the neuron to do the same


### Now, If batch_size = 4 (4 samples at a time)
### Asked neuron to do same operation but now with newer batch_size,

## The Result will be more efficient by increasing the batch_size here
### efficiency of best fit line--> batch_size--> 1-- 4 -- 16 --32 . . .


# Now people wonder why not all samples at a time ?

# The Problem with giving the neuron All the samples at a time will lead to Overfitting

## The neural network / neuron will try to fit as good as possible all the samples at once
## This will actually lead to hurt our generalization, as it has knowledge of all the samples 

## Means, it will do pretty well to fit in with in-sample data, but it will do pretty bad, in out of sample data


# Generally batch size is btw 16-32 or 64 , rarely 128 (as per use cases)

## batch size = 32 is commonly used 

In [5]:
## Lets convert our single sampled input to a batch of inputs

# intentionally evoking a shape error for better understanding

inputs=[[11.8,-2.6,3.2, -5.0],
       [1.2,4.8,5.6,-6.1],
       [2.0, 5.0, -1.5, 0.6]]  # a batch of samples  and now a matrix not 1d vector as befor

weights = [[0.3,2,0.6, -1.2],[0.1,-2,3.6, 2.6],[0.7,0.1,1.6, -3.2]] # also a matrix 
biases=[2,0.2 ,3]

output = np.dot(inputs,weights) + biases    
print("The output of the this neuron is :", output)    

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

# Troubleshooting this error . . .

# Recall the Matrix Multiplication opeations of two matrices 

## matrix(A) * matrix(B) = matrix(C)
## The first row of the matrix A's dot product will be done with each column vectors of the matrix B and all collective output will be given to the Product/Output matrix C's 1st row

## Here in above code, inputs[0]'s (row vecotr) has 4 elements but weights[column1] (column vector) has only 3 elements

# So what do we do !!! ?


## Our goal = Input * weights + bias

### Looking at weights matrix and inputs matrix, we can conclude:-

## We need to switch the Rows and Columns of Weights Matrix

## Solution :- Transpose The Array/ Matrix

In [34]:
inputs=[[11.8,-2.6,3.2, -5.0],
       [1.2,4.8,5.6,-6.1],
       [2.0, 5.0, -1.5, 0.6]]  
weights = [[0.3,2,0.6, -1.2],[0.1,-2,3.6, 2.6],[0.7,0.1,1.6, -3.2]]  
biases=[2,0.2 ,3]

output = np.dot(inputs,np.array(weights).T) + biases    # applying transpose 
print("The output of the this layer is :\n\n", output)    

The output of the this layer is :

 [[  8.26   5.1   32.12]
 [ 22.64  -4.98  32.8 ]
 [ 10.98 -13.44   0.58]]


# Adding Another Layer

## To do this, we need another set of weights and biases

In [35]:
inputs=[[11.8,-2.6,3.2, -5.0],
       [1.2,4.8,5.6,-6.1],
       [2.0, 5.0, -1.5, 0.6]]  
weights = [[0.3,2,0.6, -1.2],[0.1,-2,3.6, 2.6],[0.7,0.1,1.6, -3.2]]  
biases=[2,0.2 ,3]

weights2 = [[0.2,-1,4.6],[3.1,4.6,1],[5,-1.3, -3.2]]   
# notice size of rows and columns reduced by 1  as the layer1 input is the same
biases2 = [-1.2,0.9 ,3.3]

layer1_outputs = np.dot(inputs,np.array(weights).T) + biases    

# outputs of layer 1 becomes the inputs of layer 2

layer2_outputs = np.dot(layer1_outputs,np.array(weights2)) + biases2    

print("The output of Layer 2 is :\n\n", layer2_outputs)


The output of Layer 2 is :

 [[176.862 -25.656 -56.388]
 [151.89  -87.288  -2.496]
 [-37.768 -72.658  38.512]]


# Now , looking at the code, we can notice, adding more layers and stuffs further will going to be hectic in the code in terms of better understandings and managements

# Need of Class and Object is required now  ( OOPs)

## Performed in next program file of Layers and Object